# Mentoría
## Análisis de datos sobre la violencia contra la mujer.

### Introducción

##### Análisis y Visualización
En la siguiente notebook, realizaremos la carga del dataset que utilizarán para el práctico de la materia. Para ello, comenzaremos con las importaciones pertinentes.
Posteriormente, se detallarán las consignas a seguir para la elaboración del informe.

In [1]:
# importación de las librerías necesarias
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [2]:
pd.set_option('display.max_columns', 150)
pd.set_option('display.max_rows', 150)
pd.set_option('max_colwidth', 151)
warnings.filterwarnings('ignore')

## Revisión general de los datos

In [3]:
# carga del dataset
url = 'https://drive.google.com/file/d/1CPlW53w9zNWWNyF_7xLDsPysKSDNVAvo/view?usp=sharing'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
dataset = pd.read_csv(path)

### Dataset

In [4]:
# aquí simplemente visualizamos algunas filas y columnas de nuestro dataset
dataset.sample(3)

,ESTUDIO,REGISTRO,CUES,FECHAINI,HORAINI,FECHAFIN,HORAFIN,DURACION,CCAA,PROV,MUN,DISTR,SECCION,CAPITAL,TAMUNI,COORDINADOR,ENTREV,M0P0,M0P1,M0P2,M0P3,M0P4,M0P4A,M0P4B,M0P4C,M0P5,M0P5A,M0P6,M0P7_1,M0P7_2,M0P7_3,M0P7_4,M0P7_5,M0P7_6,M0P7_7,M0P7_8,M0P7_9,M0P8,M0P9,M0P10_1,M0P10_2,M0P10_3,M0P10_4,M0P10_5,M0P11_1,M0P11_2,M0P11_3,M0P11_4,M0P11_9,M0P12,M0P12A,M0P13,M0P13A,M0P14,M0P14A,M0P15,M0P16,M0P17,M0P18,M1P1_0_1,M1P1_0_2,M1P1_0_3,M1P1_0_4,M1P1_0_5,M1P1_0_6,M1P1_0_7,M1P1_0_8,M1P1_0_9,M1P1_0_10,M1P1_0_11,M1P1_A_1,M1P1_A_2,M1P1_A_3,M1P1_A_4,M1P1_A_5,...,SDE14,SDE15,SDE16_3,LUGAR,VALORACION_1,VALORACION_2,VALORACION_3,VALORACION_4,INTERVENCION,INTERVENCION_A_1,INTERVENCION_A_2,INTERVENCION_A_3,INTERVENCION_A_4,INTERVENCION_A_5,INTERVENCION_A_6,INTERVENCION_A_7,INTERVENCION_A_8,INTERVENCION_A_9,TARJETAS,OCULTACION,ESTUDIOSPAR,ESTUDIOS,OCUMAR11,RAMA09,OCUPAPP,RAMAPP,PESO,SITULAB,M1P2,M5P1F_9,M5P1F_10,M5P1F_11,M5P1F_12,M5P1F_13,M5P1F_14,M5P1F_99,M5P1G_1,M5P1G_2,M5P1G_3,M5P1G_4,M5P1G_9,SDE1,SDE2,SDE3,SDE4,SDE4A,ESTUDIOSP,SDE5A_1,SDE5A_2,SDE7,SDE8,SDE8A,SDE9,SDE9A,SDE9B,SDE9D,SDE10,SDE10A_1,SDE10A_2,SDE10A_3,SDE10A_4,SDE10A_5,SDE10A_6,SDE10A_7,SDE10A_8,SDE10A_9,SDE10A_10,SDE10A_11,SDE10A_12,SDE10A_13,SDE10A_99,SDE11,SDE16_1,SDE16_2,PESOCCAA
9314,3235,176054,9435,22/11/2019,14:16:21,22/11/2019,14:23:31,429,Murcia (Región de),Murcia,Cartagena / Palmas de Gran Canaria (Las),Anonimizado,Anonimizado,Otros municipios,100.001 a 400.000 habitantes,C2238,Anonimizado,Trabaja,Todos o casi todos los días,Sí,Sí,No,N.P.,N.P.,N.P.,No,N.P.,Bueno,,,,,,,,Menciona,,No,No,No,No,No,No,No,,,Menciona,,,No,N.P.,N.P.,N.P.,2 parejas,Solo hombres,No,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,...,Sí,8,No menciona,En la puerta de la vivienda,No menciona,No menciona,No menciona,Menciona,No,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,Sólo ha usado alguna,No con toda seguridad,N.P.,Secundaria 1ª etapa,"Trabajadoras de los servicios de restauración, personales, p",Servicios,,,0.64913,OCUPADAS,0,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,30,La nacionalidad española,España,"Sí, ha ido a la escuela",ESO,N.C.,,,"Asalariado/a fijo/a (a sueldo, comisión, jornal, etc. con ca",Salario del trabajo por cuenta ajena,No tengo ingresos (otros) personales,La persona entrevistada,,,,4,,,Menciona,,,,Menciona,,,,,,,,De 1.801 a 2.400 &euro;,Menciona,No menciona,1.01226
9366,3235,176684,9492,22/11/2019,15:48:47,22/11/2019,16:07:59,1151,Rioja (La),Rioja (La),Mun.<=100.000 hab. no capitales de CA o provincia,Anonimizado,Anonimizado,Otros municipios,10.001 a 50.000 habitantes,C250,Anonimizado,Trabajo doméstico no remunerado,Todos o casi todos los días,Sí,Sí,Sí,No,N.P.,N.P.,Sí,2 menores,Bueno,,,,,,,,Menciona,,No,No,No,Sí,No,No,No,,,,Menciona,,No,N.P.,N.P.,N.P.,2 parejas,Solo hombres,No,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,...,Sí,6,No menciona,En el interior de la vivienda,No menciona,No menciona,No menciona,Menciona,No,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,Las he leído yo,No con toda seguridad,N.P.,Secundaria 2ª etapa,Técnicas; profesionales de apoyo,Servicios,,,0.15354,NO OCUPADAS,0,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,63,Solo otra nacionalidad,Colombia,"Sí, ha ido a la escuela",Bachillerato (LOGSE),N.C.,10,0,"Asalariado/a eventual o interino/a (a sueldo, comisión, jorn",Pensión de jubilación,No tengo ingresos (otros) personales,(NO LEER) La persona entrevistada y otra casi a partes igual,,,,4,,,,,Menciona,,,,Menciona,,,,,,De 1.201 a 1.800 &euro;,No menciona,Menciona,0.89349
8878,3235,168324,8995,17/11/2019,17:45:42,17/11/2019,18:04:24,1121,Melilla (Ciudad Autónoma de),Melilla,Ceuta / Melilla,Anonimizado,Anonimizado,Capital de CC.AA.,50.001 a 100.000 habitantes,C842,Anonimizado,Trabaja,Todos o casi todos los días,Sí,Sí,Sí,Sí,3 hijos/as,3 hijos/as,No,N.P.,Muy bueno,,,,,,,,Menciona,,No,No,No,No,No,No,No,,,,Menciona,,No,N.P.,N.P.,N.P.,1 pareja,Solo hombres,Sí,"Sí, viven en el mismo domicilio",Casada,Entre 11 y 20 años,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,N.P.,N.P.,N.P.,N.P.,N.P.,...,Sí,5,No menciona,En la puerta de la vivienda,No menciona,No menciona,No menciona,Menciona,No,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,Las he leído yo,Creo que no,Secundaria 1ª etapa,Primaria,Ocupaciones elementales,Servicios,Ocupaciones militares,Servicios,0.03973,OCUPADAS,0,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,N.P.,33,Solo otra nacionalidad,Marruecos,"Sí, ha ido a la escuela",Educación Primaria (LOGSE),Secundaria 1ª etapa,,,"Asalariado/a fijo/a (a sueldo, comisión, jornal, etc. con ca",No tengo ingresos (otros) personales,,Otra persona,Esa persona es su cónyuge o pareja,Trabaja,"Asalariado/a fijo/a (a sueldo, comisión, jornal, etc. con ca",5,Menciona,,,,Menciona,,,,,,,,,,(NO LEER) N.S.,No menciona,Menciona,0.99035

In [5]:
# podemos ver de que tipo son los features
data_types = dataset.dtypes
data_types = pd.DataFrame(data_types)
data_types = data_types.rename(columns = {0:'ReadingDataType'})
data_types.index.names = ['FieldName']
data_types

          ReadingDataType
FieldName
ESTUDIO             int64
REGISTRO            int64
CUES                int64
FECHAINI           object
HORAINI            object
...                   ...
SDE10A_99          object
SDE11              object
SDE16_1            object
SDE16_2            object
PESOCCAA          float64

[1121 rows x 1 columns]

#### Aclaraciones
Como se pudo ver anteriormente, los nombres de las columnas de nuestro dataset están codificadas, para ver a que pregunta corresponde cada variable lo pueden consultar en el siguiente archivo:
https://drive.google.com/file/d/1YsKVIU6CALdINXRcsJuCDtesLvrcsUFD/view?usp=sharing

También se puede observar que según que tipo de pregunta es como se nombraron las variables, por ejemplo, las preguntas relacionadas con la violencia en la pareja actual tienen nombre de variable que comienzan con "M1".

Además en casos de preguntas de múltiples opciones, a estas se le agrega al código de la variable un índice que indica la opción de repuesta a elegir. 

Esto nos puede ayudar para analizar casos más simples.

### Algunos ejemplos

Veamos algunas variables como ejemplo.

Tomemos la pregunta M0P0 "Frecuencia con que se han sufrido diferentes comportamientos de la pareja actual: violencia psicológica (control social)". Esta es una pregunta de múltiple opción. Entonces las columnas que nos interesan son las que tienen por nombre: 

M1P1_0_1,M1P1_0_2,...,M1P1_0_11.

In [6]:
cols_M1P1 = [col for col in dataset.columns if 'M1P1_0_' in col]

Así podemos trabajar con un dataset más chico seleccionando estas columnas

In [7]:
dataset_M1P1 = dataset[cols_M1P1]
display(dataset_M1P1)

,M1P1_0_1,M1P1_0_2,M1P1_0_3,M1P1_0_4,M1P1_0_5,M1P1_0_6,M1P1_0_7,M1P1_0_8,M1P1_0_9,M1P1_0_10,M1P1_0_11
0,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca
1,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca
2,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca
3,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca
4,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca
...,...,...,...,...,...,...,...,...,...,...,...
9563,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca
9564,Nunca,Nunca,Algunas veces,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca
9565,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca
9566,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca
9567,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca,Nunca

De aquí, un primer análisis que podemos hacer es contar la cantidad de respuestas

In [8]:
ans_M1P1 = dataset_M1P1.apply(pd.Series.value_counts, axis=0)
ans_M1P1

,M1P1_0_1,M1P1_0_2,M1P1_0_3,M1P1_0_4,M1P1_0_5,M1P1_0_6,M1P1_0_7,M1P1_0_8,M1P1_0_9,M1P1_0_10,M1P1_0_11
Algunas veces,130,67,214,217,228,165,87,65,87,42,27
Frecuentemente,35,21,89,67,63,39,54,26,34,30,11
N.C.,6,5,4,6,6,7,7,30,30,7,29
N.P.,3005,3005,3005,3005,3005,3005,3005,3005,3005,3005,3005
Nunca,6392,6470,6256,6273,6266,6352,6415,6442,6412,6484,6496

## Análisis y Visualización - Consigna

### General
Se propone la elaboración de un informe que deberá entregarse en formato html, pdf o markdown y deberá apuntar a un público técnico, pero sin conocimientos específicos en el tema. Añadir gráficos y conclusiones obtenidas durante el desarrollo del práctico.

### Análisis descriptivo
- Entender qué tipos de features poseen los dataset, qué significan y cómo se relacionan entre ellos.
- Identificar algunos features de interés. 

### Análisis estadístico
- Seleccionar algunos features que crean relevantes para el problema. Utilizar los gráficos y cálculos que le parezcan más apropiados para llegar a las conclusiones.

    - ¿Existen outliers para estos features?
    - ¿Hay valores faltantes?
    - ¿Hay valores que no corresponden?
    - ¿Que decisión tomarían para completar o eliminar estos outliers y faltantes?
    - ¿Cómo es la distribución de las variables en el dataset?
    

- ¿Existe correlación entre algunas de las variables?